---
- name: Set fact with release_str if release_id is set
  ansible.builtin.set_fact:
    release_str: "-{{ release_id }}"
  when: release_id is defined

- name: Print the storage directory
  ansible.builtin.debug:
    msg: "Variable storage_dir is {{ storage_dir }}"

#- name: Print the isolation paths (defined in AAP job settings)
  #ansible.builtin.debug:
    #msg: "Variable AWX_ISOLATION_SHOW_PATHS is {{ AWX_ISOLATION_SHOW_PATHS }}"
    
#- name: Pause for 5 minutes to help debugging
  #ansible.builtin.pause:
    #minutes: 5

- name: Start image download
  ansible.builtin.get_url:
    url: "{{ image_url }}"
    dest: "{{ image_path }}"
    mode: "0644"
  loop: "{{ compose_status_request.results }}"
  loop_control:
    label: "{{ image_path | default('N/A') }}"
  when:
    - item.json is defined
    - item.json.image_status.status == "success"
    - item.json.image_status.upload_status.status == "success"
  vars:
    image_url: "{{ item.json.image_status.upload_status.options.url }}"
    image_path: "{{ storage_dir | default('.') }}/{{ item.json.request.image_name }}{{ release_str | default('') }}.qcow2"
  async: 600
  poll: 0
  register: download

- name: Confirm image download completed
  ansible.builtin.async_status:
    jid: "{{ jobid }}"
  register: job_result
  when: jobid
  until: job_result.finished
  retries: 10
  delay: 60
  loop: "{{ download.results }}"
  loop_control:
    label: "{{ item.item.json.request.image_name | default('N/A') }}"
  vars:
    jobid: "{{ item.ansible_job_id | default(false) }}"

- name: Get stats of a file
  ansible.builtin.stat:
    path: "/etc/pki/ca-trust/bblasco-rhel-9-lamp-ib.qcow2"
  register: file_status

- name: Show the file status
  ansible.builtin.debug:
    msg: "File Status is: {{ file_status }}"
